### ISSUE TITLE
Add ability to opt out of channel linking

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/auto-link-channel-skill#96]
Currently auto channel linking is all or nothing. Is it possible to opt-out for certain repos?

**Comment by cdupuis** [comment]
This skill has the repo filter for this. Although opting out isn't really a thing with our current repo filter UX. But that's not an issue with this skill here but rather a UI concern.

**Comment by cdupuis** [comment]
@ddgenome should we track this at https://github.com/atomisthq/design/issues/262? Or do you feel strongly about adding some special to this skill here?

**Comment by ddgenome** [comment]
I did not realize this skill used the repo selector. I thought it just linked all new repos. I'll close this.
